# Generated by Django 4.2.7 on 2024-01-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contruct_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contructus',
            options={'verbose_name_plural': 'Contruct US'},
        ),
    ]
